# Dependent Modules

In [1]:
# import required modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Variable definitions
| Variable abbv. | Explanation |
| ---- | ---- |
| PTCT | Public Trade Company Types |
| MDC | Missing Data Count |
| ML | Management layer |
|

In [9]:
# read puclic trade company types data
PTCT = pd.read_excel('../data/raw/上市公司行业类型.xlsx')

PTCT.columns = [col.replace('\n', '') for col in PTCT.columns]
PTCT.head(5)

,证券代码,证券简称,所属行业名称[行业标准] 申万行业[行业级别] 一级行业,上市日期,支付给职工以及为职工支付的现金[报告期] 2010年报[报表类型] 合并报表[单位] 元,支付给职工以及为职工支付的现金[报告期] 2011年报[报表类型] 合并报表[单位] 元,支付给职工以及为职工支付的现金[报告期] 2012年报[报表类型] 合并报表[单位] 元,支付给职工以及为职工支付的现金[报告期] 2013年报[报表类型] 合并报表[单位] 元,支付给职工以及为职工支付的现金[报告期] 2014年报[报表类型] 合并报表[单位] 元,支付给职工以及为职工支付的现金[报告期] 2015年报[报表类型] 合并报表[单位] 元,...,员工总数[交易日期] 2018-12-31,年末所得税率[年度] 2010,年末所得税率[年度] 2011,年末所得税率[年度] 2012,年末所得税率[年度] 2013,年末所得税率[年度] 2014,年末所得税率[年度] 2015,年末所得税率[年度] 2016,年末所得税率[年度] 2017,年末所得税率[年度] 2018
0,000001.SZ,平安银行,银行,1991-04-03,3.747634e+09,5.287265e+09,7.176205e+09,9.660000e+09,1.217500e+10,1.287100e+10,...,33708.0,22.0,24.0,25.0,25.0,25.0,25.0,25.0,25.0,25.0
1,000002.SZ,万科A,房地产,1991-01-29,1.848828e+09,2.480848e+09,2.908877e+09,3.472696e+09,5.132633e+09,5.046300e+09,...,104300.0,22.0,24.0,25.0,25.0,25.0,25.0,25.0,25.0,25.0
2,000004.SZ,国华网安,计算机,1991-01-14,1.353200e+07,1.497066e+07,1.669537e+07,1.850977e+07,1.607097e+07,1.483402e+07,...,210.0,22.0,24.0,25.0,25.0,25.0,25.0,25.0,25.0,25.0
3,000005.SZ,ST星源,公用事业,1990-12-10,3.088473e+07,3.898805e+07,3.206375e+07,3.084465e+07,2.833883e+07,3.361960e+07,...,745.0,22.0,24.0,25.0,25.0,25.0,25.0,25.0,25.0,25.0
4,000006.SZ,深振业A,房地产,1992-04-27,5.417853e+07,6.921623e+07,7.619825e+07,8.350216e+07,9.704156e+07,8.391737e+07,...,377.0,20.0,24.0,25.0,25.0,25.0,25.0,25.0,25.0,25.0

In [12]:
# could number of missing values in each column
MDC = pd.DataFrame(PTCT.isnull().sum(), columns=['Missing Data Count'])
MDC.tail(5)

                 Missing Data Count
年末所得税率[年度] 2014                1069
年末所得税率[年度] 2015                 875
年末所得税率[年度] 2016                 650
年末所得税率[年度] 2017                 347
年末所得税率[年度] 2018                  15

In [13]:
PTCT.columns

Index(['证券代码', '证券简称', '所属行业名称[行业标准] 申万行业[行业级别] 一级行业', '上市日期',
       '支付给职工以及为职工支付的现金[报告期] 2010年报[报表类型] 合并报表[单位] 元',
       '支付给职工以及为职工支付的现金[报告期] 2011年报[报表类型] 合并报表[单位] 元',
       '支付给职工以及为职工支付的现金[报告期] 2012年报[报表类型] 合并报表[单位] 元',
       '支付给职工以及为职工支付的现金[报告期] 2013年报[报表类型] 合并报表[单位] 元',
       '支付给职工以及为职工支付的现金[报告期] 2014年报[报表类型] 合并报表[单位] 元',
       '支付给职工以及为职工支付的现金[报告期] 2015年报[报表类型] 合并报表[单位] 元',
       '支付给职工以及为职工支付的现金[报告期] 2016年报[报表类型] 合并报表[单位] 元',
       '支付给职工以及为职工支付的现金[报告期] 2017年报[报表类型] 合并报表[单位] 元',
       '支付给职工以及为职工支付的现金[报告期] 2018年报[报表类型] 合并报表[单位] 元',
       '非独立董事人数[交易日期] 2010-12-31', '非独立董事人数[交易日期] 2011-12-31',
       '非独立董事人数[交易日期] 2012-12-31', '非独立董事人数[交易日期] 2013-12-31',
       '非独立董事人数[交易日期] 2014-12-31', '非独立董事人数[交易日期] 2015-12-31',
       '非独立董事人数[交易日期] 2016-12-31', '非独立董事人数[交易日期] 2017-12-31',
       '非独立董事人数[交易日期] 2018-12-31', '公司监事(历任)[交易日期] 2010-12-31',
       '公司监事(历任)[交易日期] 2011-12-31', '公司监事(历任)[交易日期] 2012-12-31',
       '公司监事(历任)[交易日期] 2013-12-31', '公司监事(历任)[交易日期] 2014-12-31',
       '公司监事(历任)[交易日期] 2015-12-31', '公司监事(历任)[交易日期] 2016-12-31',
       '公司监事(历任)[交易日期] 2017-12-31', '公司监事(历任)[交易日期] 2018-12-31',
       '高管人数[交易日期] 2010-12-31', '高管人数[交易日期] 2011-12-31',
       '高管人数[交易日期] 2012-12-31', '高管人数[交易日期] 2013-12-31',
       '高管人数[交易日期] 2014-12-31', '高管人数[交易日期] 2015-12-31',
       '高管人数[交易日期] 2016-12-31', '高管人数[交易日期] 2017-12-31',
       '高管人数[交易日期] 2018-12-31', '管理层年度薪酬总额[年度] 2010[单位] 万元',
       '管理层年度薪酬总额[年度] 2011[单位] 万元', '管理层年度薪酬总额[年度] 2012[单位] 万元',
       '管理层年度薪酬总额[年度] 2013[单位] 万元', '管理层年度薪酬总额[年度] 2014[单位] 万元',
       '管理层年度薪酬总额[年度] 2015[单位] 万元', '管理层年度薪酬总额[年度] 2016[单位] 万元',
       '管理层年度薪酬总额[年度] 2017[单位] 万元', '管理层年度薪酬总额[年度] 2018[单位] 万元',
       '员工总数[交易日期] 2010-12-31', '员工总数[交易日期] 2011-12-31',
       '员工总数[交易日期] 2012-12-31', '员工总数[交易日期] 2013-12-31',
       '员工总数[交易日期] 2014-12-31', '员工总数[交易日期] 2015-12-31',
       '员工总数[交易日期] 2016-12-31', '员工总数[交易日期] 2017-12-31',
       '员工总数[交易日期] 2018-12-31', '年末所得税率[年度] 2010', '年末所得税率[年度] 2011',
       '年末所得税率[年度] 2012', '年末所得税率[年度] 2013', '年末所得税率[年度] 2014',
       '年末所得税率[年度] 2015', '年末所得税率[年度] 2016', '年末所得税率[年度] 2017',
       '年末所得税率[年度] 2018'],
      dtype='object')